### ISSUE TITLE
V2Ray Servers

### ISSUE THREAD

**Issue by freejohn123** [net4people/bbs#145] opened 2022-10-24 01:05 UTC
در این کانال سرورهای اختصاصی V2Ray به همراه اپلیکیشن‌های مورد نیاز برای اتصال قرار داده می‌شود.

محتوای این کانال کاملا رایگان است و خواهد بود.

به جهت افزایش کارایی و سرعت این VPN، سرورها از شرکت‌های معتبر خریداری شده است.

به امید پیروزی✌️

In this channel, dedicated V2Ray servers are placed along with the applications required for connection.

The content of this channel is and will be completely free.

In order to increase the efficiency and speed of this VPN, servers have been purchased from reputable companies.

Hoping for victory ✌️

https://t.me/v2ray_freedomiran

**Comment by wkrp** [comment] 2022-10-24 16:31
> How can we know it's not the islamic republic regime setting these servers up to catch people?

It's a good point. I think we don't have the resources to vet whether such a source of information is trustworthy. If you don't mind, I'll close the issue.

Sharing lists of proxies is not really the purpose of this forum. The key is that we are focused on **research** and **development**. User reports are welcome, if they help bring understanding of the causes of blocking; developers and deployers are welcome to troubleshoot their deployments and share their findings; but sharing proxy lists is better done in other venues. If anyone has information *about* the proxies being shared, that is still welcome information: for example if you find one of the servers to be blocked, or unblocked, only accessible over certain protocols, etc.

**Closed by wkrp** 2022-10-24 16:31 UTC
Labels: Iran
